apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-service-reader
  namespace: default
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-service-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: knative-service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: dprotaso/mcp-e8c811ec355107325cb529bafd798151@sha256:648b273f877905217612f6450c54cd549a89c8d7e69b37638cf705088b4951eb

---
